# This file was generated by GoReleaser. DO NOT EDIT.
cask "qodercli" do
  # Create installation source marker after installation for update detection
  postflight do
    require 'fileutils'
    require 'time'

    # Core installation steps (must succeed, same as original version)
    marker = staged_path/'.qodercli-install-resource'
    File.write(marker, "homebrew-cask")
    marker.chmod(0644)
    (staged_path/"qodercli").chmod(0755)
    bin_binary = HOMEBREW_PREFIX/"bin"/"qodercli"
    ENV['QODER_CLI_INSTALL'] = '1'

    # Logging and verification (failures here won't block installation)
    begin
      # Setup logging directory
      log_dir = File.expand_path("~/.qoder/logs")
      FileUtils.mkdir_p(log_dir)
      timestamp = Time.now.strftime("%Y%m%d_%H%M%S")
      log_file = File.join(log_dir, "qodercli_install_homebrew_#{timestamp}.log")

      # Create and write to log file
      log = File.open(log_file, 'w')
      log.puts "Installation started at #{Time.now.iso8601}"
      log.puts "Installation method: homebrew"
      log.puts "Platform: #{RUBY_PLATFORM}"
      log.puts "Homebrew prefix: #{HOMEBREW_PREFIX}"
      log.puts "================================\n"
      log.flush

      # Create symlink to latest log
      latest_log = File.join(log_dir, "qodercli_install.log")
      File.unlink(latest_log) if File.exist?(latest_log) || File.symlink?(latest_log)
      File.symlink(log_file, latest_log)

      # Verify installation and get version
      version_output = `#{bin_binary} --version 2>&1`.strip
      if $?.success?
        log.puts "Installation verified successfully"
        log.puts "Version: #{version_output}"
        puts "\n🎉 #{version_output} installed successfully!"
      else
        log.puts "[ERROR] Version check failed: #{version_output}"
        puts "\n⚠️ Installation completed but version check failed"
      end

      log.puts "\nInstallation completed at #{Time.now.iso8601}"
      log.close

      puts "Get started: qodercli --help"
      puts "Installation log: #{log_file}\n"
    rescue => e
      # Logging failed, but installation succeeded
      puts "\n🎉 Qoder CLI installed successfully!"
      puts "Get started: qodercli --help"
      puts "(Note: Installation log could not be created: #{e.message})\n"
    end
  end

  name "qodercli"
  desc "Qoder AI CLI tool - Terminal-based AI assistant for code development"
  homepage "https://qoder.com"
  version "0.1.29"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qodercli"

  on_macos do
    on_intel do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_darwin_amd64.zip"
      sha256 "925790fb4c296a550e62a48de6d46942e5002024083ba8b3447db1dee4bc6a9c"
    end
    on_arm do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_darwin_arm64.zip"
      sha256 "33f13311a5f6ab88f6c2c35475a0eac49822fb47046c4aa49b752599e46f1f17"
    end
  end

  on_linux do
    on_intel do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_linux_amd64.tar.gz"
      sha256 "d46c2473c189249f9957dd38064e2580b91c437cd96cef318368d4eec5d08ede"
    end
    on_arm do
      url "https://download.qoder.com/qodercli/releases/#{version}/qodercli_#{version}_linux_arm64.tar.gz"
      sha256 "f2bf01e3459d57922ea510fb7e4b45f76951a1503495eac51f3962074e49533a"
    end
  end

  # No zap stanza required
end
